CREATE TABLE USUARIO(
    NICKNAME VARCHAR(20),
    NOMBRE_APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    PRIMARY KEY(NICKNAME)
);

-- TABLA GENERO
CREATE TABLE GENERO(
    ID INT AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

--TABLA MUSICA
CREATE TABLE MUSICA(
    ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    AUTOR VARCHAR(100),
    NICKNAME VARCHAR(20),
    GENERO_ID INT,
    PRIMARY KEY(ID)
);

ALTER TABLE MUSICA ADD CONSTRAINT fk_musica_usuario
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

ALTER TABLE MUSICA ADD CONSTRAINT fk_musica_genero
FOREIGN KEY(GENERO_ID) REFERENCES GENERO(ID);

CREATE TABLE LISTA_REPRODUCCION(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    NICKNAME VARCHAR(20),
    PRIMARY KEY(ID)
);

ALTER TABLE LISTA_REPRODUCCION ADD CONSTRAINT fk_lista_usuario
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

--TABLA LISTA MUSICA
CREATE TABLE LISTA_MUSICA(
    LISTA_ID INT,
    MUSICA_ID INT,
);

ALTER TABLE LISTA_MUSICA ADD CONSTRAINT pk_lista_musica
PRIMARY KEY(LISTA_ID, MUSICA_ID);

ALTER TABLE LISTA MUSICA ADD CONSTRAINT fk_listac_listar
FOREIGN KEY(LISTA_ID) REFERENCES LISTA_REPRODUCCION(ID);

ALTER TABLE LISTA_MUSICA ADD CONSTRAINT fk_listac_musica
FOREIGN KEY(MUSICA_ID) REFERENCES MUSICA(ID);